import {
  Activity,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  Ban,
  BellRing,
  Briefcase,
  Building2,
  Calendar,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronRight,
  CircleCheck,
  CircleCheckBig,
  CircleHelp,
  CirclePause,
  CircleX,
  ClipboardList,
  Clock,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  Footprints,
  Globe,
  Heart,
  HeartPulse,
  History,
  Hourglass,
  House,
  Info,
  Landmark,
  LayoutDashboard,
  ListOrdered,
  LoaderCircle,
  LocateFixed,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map,
  MapPin,
  MapPinCheck,
  Megaphone,
  Menu,
  Navigation,
  Phone,
  Pill,
  Play,
  Printer,
  Power,
  Radio,
  RefreshCw,
  Scissors,
  Search,
  SearchX,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Stethoscope,
  Store,
  Ticket,
  TicketCheck,
  TicketPlus,
  Timer,
  TriangleAlert,
  User,
  UserCheck,
  UserRound,
  Users,
  UsersRound,
  Volume2,
  Wrench,
  X,
  Zap,
} from 'lucide-react'

/**
 * Registre centralisé des icônes (Lucide — https://lucide.dev/icons).
 * Toujours passer par ces clés : <Icon name={ICONS.ticket} />
 */
export const ICONS = Object.freeze({
  // Navigation
  home: House,
  places: Building2,
  store: Store,
  ticket: Ticket,
  ticketCheck: TicketCheck,
  ticketPlus: TicketPlus,
  back: ArrowLeft,
  forward: ArrowRight,
  down: ArrowDown,
  arrowUpRight: ArrowUpRight,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  external: ExternalLink,
  dashboard: LayoutDashboard,
  queue: ListOrdered,
  history: History,
  login: LogIn,
  logout: LogOut,
  help: CircleHelp,
  menu: Menu,
  filters: SlidersHorizontal,

  // Utilisateur / formulaire
  person: User,
  account: UserRound,
  personPin: MapPinCheck,
  phone: Phone,
  smartphone: Smartphone,
  mail: Mail,
  lock: Lock,
  visibility: Eye,
  visibilityOff: EyeOff,
  search: Search,
  searchOff: SearchX,
  globe: Globe,

  // Statuts / feedback
  check: Check,
  checkAll: CheckCheck,
  checkCircle: CircleCheck,
  taskAlt: CircleCheckBig,
  close: X,
  cancel: CircleX,
  block: Ban,
  info: Info,
  warning: TriangleAlert,
  verified: BadgeCheck,
  shield: ShieldCheck,
  hourglass: Hourglass,
  sync: RefreshCw,
  spinner: LoaderCircle,
  timer: Timer,
  schedule: Clock,
  calendar: Calendar,
  bolt: Zap,
  sensors: Radio,
  activity: Activity,
  sparkles: Sparkles,
  list: ClipboardList,
  print: Printer,
  download: Download,

  // File / appel
  campaign: Megaphone,
  bell: BellRing,
  groups: Users,
  group: UsersRound,
  pause: CirclePause,
  play: Play,
  power: Power,
  volume: Volume2,
  walk: Footprints,
  next: UserCheck,

  // Favoris / localisation
  heart: Heart,
  location: MapPin,
  map: Map,
  navigation: Navigation,
  locate: LocateFixed,

  // Catégories d'établissements
  pharmacy: Pill,
  medical: Stethoscope,
  health: HeartPulse,
  administration: Landmark,
  bank: Briefcase,
  beauty: Scissors,
  services: Wrench,
})
