import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  BadgeCheck,
  Ban,
  BellRing,
  Building2,
  Check,
  CircleCheck,
  CircleCheckBig,
  CircleHelp,
  CirclePause,
  CircleX,
  Clock,
  ExternalLink,
  Eye,
  EyeOff,
  Footprints,
  History,
  Hourglass,
  House,
  Info,
  LayoutDashboard,
  ListOrdered,
  LoaderCircle,
  Lock,
  LogOut,
  Mail,
  MapPin,
  MapPinCheck,
  Megaphone,
  Phone,
  Pill,
  Play,
  Power,
  Radio,
  RefreshCw,
  Search,
  SearchX,
  ShieldCheck,
  Star,
  Stethoscope,
  Store,
  Ticket,
  Timer,
  TriangleAlert,
  User,
  UserCheck,
  Users,
  UsersRound,
  Volume2,
  X,
  Zap,
} from 'lucide-react'

/**
 * Registre centralisé des icônes (Lucide — https://lucide.dev/icons).
 * Toujours passer par ces clés : <Icon name={ICONS.ticket} />
 */
export const ICONS = Object.freeze({
  // Navigation
  home: House,
  places: Building2,
  store: Store,
  ticket: Ticket,
  back: ArrowLeft,
  forward: ArrowRight,
  down: ArrowDown,
  external: ExternalLink,
  dashboard: LayoutDashboard,
  queue: ListOrdered,
  history: History,
  logout: LogOut,
  help: CircleHelp,

  // Utilisateur / formulaire
  person: User,
  personPin: MapPinCheck,
  phone: Phone,
  mail: Mail,
  lock: Lock,
  visibility: Eye,
  visibilityOff: EyeOff,
  search: Search,
  searchOff: SearchX,

  // Statuts / feedback
  check: Check,
  checkCircle: CircleCheck,
  taskAlt: CircleCheckBig,
  close: X,
  cancel: CircleX,
  block: Ban,
  info: Info,
  warning: TriangleAlert,
  verified: BadgeCheck,
  shield: ShieldCheck,
  hourglass: Hourglass,
  sync: RefreshCw,
  spinner: LoaderCircle,
  timer: Timer,
  schedule: Clock,
  bolt: Zap,
  sensors: Radio,

  // File / appel
  campaign: Megaphone,
  bell: BellRing,
  groups: Users,
  group: UsersRound,
  pause: CirclePause,
  play: Play,
  power: Power,
  volume: Volume2,
  walk: Footprints,
  next: UserCheck,

  // Établissements
  pharmacy: Pill,
  medical: Stethoscope,
  location: MapPin,
  star: Star,
})
